name: Release-plz

on:
  push:
    branches: [main]

jobs:
  release-plz:
    if: github.repository_owner == 'stadiamaps'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
      pull-requests: write
    concurrency:
      group: release-plz-${{ github.ref }}
      cancel-in-progress: false
    steps:
      - uses: actions/checkout@v6
        with: { fetch-depth: 0 }

      - name: Publish to crates.io if crate version is newer
        uses: release-plz/action@v0.5
        id: release
        with: { command: release }
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_PLZ_TOKEN }}
          
      - if: ${{ steps.release.outputs.releases_created == 'false' }}
        name: Create PR proposing new version and changelog
        uses: release-plz/action@v0.5
        with: { command: release-pr }
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_PLZ_TOKEN }}
